# Generated by Django 3.1 on 2020-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_number', models.CharField(default='A0000000A', max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('year', models.PositiveSmallIntegerField(default=1)),
                ('course', models.CharField(max_length=256)),
            ],
        ),
    ]
