# Generated by Django 3.1 on 2020-09-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200830_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='matric_number',
            new_name='matriculation_number',
        ),
    ]
