# Generated by Django 3.1 on 2020-09-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('students', '0002_auto_20200830_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_to_student', to='modules.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_module', to='students.student')),
            ],
            options={
                'unique_together': {('module', 'student')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.ManyToManyField(related_name='students', through='students.TakeModule', to='modules.Module'),
        ),
    ]
