# Generated by Django 3.1 on 2020-09-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_cap',
            new_name='max_capacity',
        ),
    ]
