# Generated by Django 3.1 on 2020-09-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
