# Generated by Django 3.1 on 2020-09-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200911_1450'),
        ('modules', '0002_auto_20200911_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
